rootProject.name = "sigir-sampling-bias-ltr"

// Sub-projects to include in the build.
// (Maintain lexicographic order.)
include("source")
include("source:chatnoir")
include("source:clueweb-webgraph")
include("source:corpus-url")
include("source:corpus-url-parser")
include("source:correlation")
include("source:data")
include("source:domain-stats")
include("source:evaluation")
include("source:experiment")
include("source:features-clueweb09")
include("source:features-letor")
include("source:groups")
include("source:groups-canonicalization")
include("source:ltr")
include("source:ltr-files")
include("source:math")
include("source:model")
include("source:search")
include("source:tasks")
